const Labels = {
  search: 'Search',
  loading: 'Loading...',
  error: 'ERROR!',
  x: 'X',
  About: 'About',
  Stats: 'Stats',
  arrow: '<',
  total: 'Total',
  speed: 'Speed',
  spDefence: 'Sp. Defence',
  spAttack: 'Sp. Attack',
  defence: 'Defence',
  attack: 'Attack',
  HP: 'HP',
  baseStats: 'Base Stats',
  height: 'Height',
  weight: 'Weight',
  baseExp: 'Base Exp',
  pokedexData: 'Pokédex Data',
  abilities: 'Abilities',
  breeding: 'Breeding',
  pokedex: 'Pokédex',
  baseURL: 'https://pokeapi.co/api/v2',
  msgError: 'Please check your internet connection!',
  habitat: 'Habitat',
  ability: 'Ability',
  abilityMain: 'Main Ability',
  statsDescription: "The ranges show the Pokémon's Base Stats. And the rest of the unpainted line is a scale comparison.",
  noDescription: '(no description)',
  msgSearchError: 'Sorry, the Pokémon was not found.',
  msgFill: 'Please fill in the search field!',
  msgVerify: 'Please check your search!'
};

export { Labels };
